name = "halo"
author = "Jacob Williams"
copyright  = "Copyright (c) 2022, Jacob Williams"
license = "BSD-3"
description = "Halo orbit solver"
homepage = "https://github.com/jacobwilliams/halo"
keywords = ["orbital mechanics", "nrho", "cr3bp"]

[build]
auto-executables = true
auto-examples = true
auto-tests = true
external-modules = "dqrm_mod"
link = ["lapack", "blas"]

[dependencies]
fortran-astrodynamics-toolkit = { git = "https://github.com/jacobwilliams/Fortran-Astrodynamics-Toolkit", tag = "0.7" }
NumDiff = { git = "https://github.com/jacobwilliams/NumDiff", tag = "1.8.0" }
ddeabm = { git = "https://github.com/jacobwilliams/ddeabm", tag = "3.0.0" }
json-fortran = { git = "https://github.com/jacobwilliams/json-fortran", tag = "8.4.0" }
bspline-fortran = { git = "https://github.com/jacobwilliams/bspline-fortran", tag = "7.0.0" }
pyplot-fortran = { git = "https://github.com/jacobwilliams/pyplot-fortran", tag = "3.2.0" }
fortran-search-and-sort = { git = "https://github.com/jacobwilliams/fortran-search-and-sort", tag = "1.0.0" }
nlesolver-fortran = { git = "https://github.com/jacobwilliams/nlesolver-fortran", tag = "2.2.0" }
argv-fortran = { git = "https://github.com/jacobwilliams/argv-fortran", tag = "1.0.0" }
simulated-annealing = { git = "https://github.com/jacobwilliams/simulated-annealing", tag = "1.2.0" }

[library]
source-dir = "src"

[install]
library = false