name = "halo"
author = "Jacob Williams"
copyright  = "Copyright (c) 2022, Jacob Williams"
license = "BSD-3"
description = "Halo orbit solver"
homepage = "https://github.com/jacobwilliams/halo"
keywords = ["orbital mechanics", "nrho", "cr3bp"]

[build]
auto-executables = true
auto-examples = true
auto-tests = true

[dependencies]
fortran-astrodynamics-toolkit = { git = "https://github.com/jacobwilliams/Fortran-Astrodynamics-Toolkit", tag = "13075141191d78976e84dfa19ffd4342aa7936cc" }
NumDiff = { git = "https://github.com/jacobwilliams/NumDiff", tag = "cf37c94682e1a3871553c4062e1622e662b17060" }
ddeabm = { git = "https://github.com/jacobwilliams/ddeabm", tag = "3.0.0" }
json-fortran = { git = "https://github.com/jacobwilliams/json-fortran", tag = "8.2.5" }
bspline-fortran = { git = "https://github.com/jacobwilliams/bspline-fortran", tag = "6.1.0" }
pyplot-fortran = { git = "https://github.com/jacobwilliams/pyplot-fortran", tag = "3.2.0" }
fortran-search-and-sort = { git = "https://github.com/jacobwilliams/fortran-search-and-sort", tag = "1.0.0" }
fortran-csv-module = { git = "https://github.com/jacobwilliams/fortran-csv-module", tag = "1.3.0" }
nlesolver-fortran = { git = "https://github.com/jacobwilliams/nlesolver-fortran", tag = "1.2.0" }
argv-fortran = { git = "https://github.com/jacobwilliams/argv-fortran", tag = "1.0.0" }

[library]
source-dir = "src"

[install]
library = true