compute_rdot – halo
compute_rdot Function
7 statements
Source File
public function compute_rdot(rv) result(rdot)
compute rdot, which is d(rmag)/dt.
See also: compute_rdot_vecs
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(6) :: rv
rv vector (km, km/s)
Return Value real(kind=wp)
[km/s]
Called by
Source Code
    function compute_rdot(rv) result(rdot)
        real(wp),dimension(6),intent(in) :: rv !! rv vector (km, km/s)
        real(wp) :: rdot !! [km/s]
        associate(r => rv(1:3), v => rv(4:6))
            rdot = dot_product(r,v) / norm2(r)
        end associate
    end function compute_rdot
Call graph
get_problem_arrays calls compute_rdot
constraint_violations calls get_problem_arrays
initialize_the_mission calls get_problem_arrays
print_constraint_defects calls get_problem_arrays
halo_solver_main calls constraint_violations, print_constraint_defects, initialize_the_solver
initialize_the_solver calls initialize_the_mission