destroy_jpl_ephemeris_splined – halo
destroy_jpl_ephemeris_splined Subroutine
7 statements
Source File
private subroutine destroy_jpl_ephemeris_splined(me)
Type Bound
jpl_ephemeris_splined
Arguments
Type Intent Optional Attributes Name
class(jpl_ephemeris_splined), intent(inout) :: me
Calls
Called by
Source Code
    subroutine destroy_jpl_ephemeris_splined(me)
        class(jpl_ephemeris_splined),intent(inout) :: me
        call me%earth_eph_interface%destroy()
        call me%sun_eph_interface%destroy()
        call me%ssb_eph_interface%destroy()
        call me%jupiter_eph_interface%destroy()
    end subroutine destroy_jpl_ephemeris_splined
Call graph
destroy_jpl_ephemeris_splined calls destroy_body_eph_interface
destroy_body_eph_interface calls destroy_body_eph
initialize_globals calls destroy_jpl_ephemeris_splined
initialize_splinded_ephemeris calls initialize_globals