generate_pck_file – halo
generate_pck_file Subroutine
10 statements
Source File
public subroutine generate_pck_file(filename)
Generate a PCK (JSON version) to go with the BSP file. Note: this kernel can be read by jsonspice + SpiceyPy.
Reference
NAIF Integer ID codes
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
Calls
Called by
Source Code
    subroutine generate_pck_file(filename)
    character(len=*),intent(in) :: filename
    type(json_file) :: json
    call json%initialize(compress_vectors=.true.)
    call json%add('+NAIF_BODY_NAME', object_name)
    call json%add('+NAIF_BODY_CODE', object_id)
    call json%add('BODY'//int_to_string(object_id)//'_RADII', [0.001_wp, 0.001_wp, 0.001_wp])
    call json%print(filename)
    call json%destroy()
    end subroutine generate_pck_file
Call graph
generate_pck_file calls add, destroy, initialize, int_to_string
halo_solver_main calls generate_pck_file