get_real_vec – halo
get_real_vec Subroutine
14 statements
Source File
private subroutine get_real_vec(me, name, variable, found)
Get a real vector from the config file.
Type Bound
config_file
Arguments
Type Intent Optional Attributes Name
class(config_file), intent(inout) :: me
character(len=*), intent(in) :: name
name of the variable
real(kind=wp), intent(inout), dimension(:), allocatable :: variable
the variable to populate with the value
logical, intent(out), optional :: found
if the variable was in the file
Calls
Called by
Source Code
    subroutine get_real_vec(me, name, variable, found)
    class(config_file),intent(inout) :: me
    character(len=*),intent(in) :: name !! name of the variable
    real(wp),dimension(:),allocatable,intent(inout) :: variable  !! the variable to populate with the value
    logical,intent(out),optional :: found !! if the variable was in the file
    real(wp),dimension(:),allocatable :: tmp
    logical :: required  !! if the variable is required
                         !! (if required and not found, `error stop` is called)
    logical :: was_found !! local copy of `found`
    required = .not. present(found)
    call me%json%get(name, tmp, was_found); if (was_found) variable = tmp
    if (required .and. .not. was_found) &
    error stop trim(name)//' integer variable not found in config file: '//trim(me%name)
    if (present(found)) found = was_found
    end subroutine get_real_vec
Call graph
get_real_vec calls get
read_config_file calls get, read_epoch
read_epoch calls get
initialize_the_solver calls read_config_file
halo_solver_main calls initialize_the_solver