halo_solver_main – halo
halo_solver_main Subroutine
129 statements
Source File
public subroutine halo_solver_main(config_file_name, debug)
Uses
parameters_module
Main program to solve the Halo targeting problem.
Author
Jacob Williams : Sept. 2017
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: config_file_name
the config file to read
logical, intent(in) :: debug
for debugging prints
Calls
Source Code
    subroutine halo_solver_main(config_file_name,debug)
    use parameters_module
!$  use omp_lib
    implicit none
    character(len=*),intent(in) :: config_file_name  !! the config file to read
    logical,intent(in) :: debug !! for debugging prints
    type(my_solver_type) :: solver  !! an instance of the solver that we will use
    real(wp),dimension(:),allocatable :: x  !! solver opt vars vector ["forward-backward" formulation]
    integer :: m  !! number of functions
    real(wp),dimension(:),allocatable :: f  !! function vector (constraint violations)
    real(wp) :: tstart, tend  !! for timing
    real(wp) :: tstart_cpu, tend_cpu  !! for timing
    integer :: istat
    character(len=:),allocatable :: message  !! Text status message from solver
    integer :: n_segs, iseg
    real(wp),dimension(6) :: x_rotating
    character(len=:),allocatable :: mkspk_input, bsp_output, mkspk_setup, pck_output  !! filenames for mkspk
!$  integer :: tid, nthreads
    write(*,'(A)') ''
    write(*,'(A)') ' * HALO start'
!$OMP PARALLEL PRIVATE(NTHREADS, TID)
!$
!$  tid = omp_get_thread_num()
!$
!$  if (tid == 0) then
!$      nthreads = omp_get_num_threads()
!$      write(*,'(A,1X,I3)') ' * Number of OMP threads: ', OMP_get_num_threads()
!$  end if
!$
!$OMP END PARALLEL
    if (debug) then
        write(*,*) ''
        write(*,*) '----------------------'
        write(*,*) 'Initializing...'
        write(*,*) '----------------------'
        write(*,*) ''
    end if
    call solver%init(config_file_name,x)  ! initialize the solver & mission (and generate the initial guess)
    if (solver%mission%generate_plots) &
        call solver%mission%plot('guess', draw_trajectory=.true.)    ! plot the initial guess
    if (solver%mission%generate_guess_and_solution_files) &
        call solver%mission%write_optvars_to_file('guess',x)    ! write guess to a file
    !....debugging....
    ! if (solver%mission%generate_trajectory_files) &
    !     call solver%mission%plot('guess',&
    !             draw_trajectory = .false., &
    !             export_trajectory=solver%mission%generate_trajectory_files)
    !....debugging....
    if (debug) then
        call solver%mission%define_problem_size(m=m)
        allocate(f(m))
        call solver%mission%constraint_violations(x,f)
        write(*,*) ''
        write(*,*) '----------------------'
        write(*,*) 'Initial Guess...'
        write(*,*) '----------------------'
        write(*,*) ''
        write(*,'(A/,*(F30.16/))') 'x:      ', x * solver%mission%xscale    ! unscaled values
        write(*,*) ''
        write(*,'(A/,*(F30.16/))') 'f:      ', f    ! scaled values
        write(*,*) ''
    end if
    if (debug) then
        write(*,*) 'INITIAL GUESS:'
        call solver%mission%define_problem_size(n_segs=n_segs)
        do iseg = 1, n_segs
            call solver%mission%segs(iseg)%get_inputs(x0_rotating=x_rotating)
            write(*,'(I5, *(F15.6,1X))') iseg, x_rotating
        end do
    end if
    if (solver%mission%solve) then
        if (debug) then
            write(*,*) ''
            write(*,*) '----------------------'
            write(*,*) 'Solving...'
            write(*,*) '----------------------'
            write(*,*) ''
        end if
        write(*,'(A)') ' * Solving'
        write(*,*) ''
        call cpu_time(tstart_cpu)
!$      tstart = omp_get_wtime()
        call solver%solve(x)  ! call the solver
        call solver%status(istat=istat, message=message)
        call cpu_time(tend_cpu)
!$      tend = omp_get_wtime()
        call solver%mission%put_x_in_segments(x) ! populate segs with solution
    else
        call cpu_time(tstart_cpu)
        call cpu_time(tend_cpu)
        message = 'Not solved'
    end if
    if (debug) then
        write(*,*) ''
        write(*,*) '----------------------'
        write(*,*) 'Solution...'
        write(*,*) '----------------------'
        write(*,*) ''
    end if
    write(*,*) ''
    write(*,'(A)') ' * Status: '//message
    write(*,'(A,1x,F10.3,1x,a)') ' * Elapsed cpu_time: ', (tend_cpu-tstart_cpu), 'sec'
!$  write(*,'(A,1x,F10.3,1x,a)') ' * OMP wall time   : ', (tend-tstart), 'sec'
    if (solver%mission%generate_guess_and_solution_files) then
        write(*,'(A)') ' * Generate solution file'
        call solver%mission%write_optvars_to_file('solution',x) ! write solution to a file
    end if
    ! export solution to plot or trajectory file
    if (solver%mission%generate_trajectory_files .or. solver%mission%generate_plots) then
        write(*,'(A)') ' * Export solution trajectory'
        call solver%mission%plot('solution',&
                draw_trajectory=solver%mission%generate_plots, &
                export_trajectory=solver%mission%generate_trajectory_files)
    end if
    if (solver%mission%generate_kernel) then
        if (.not. solver%mission%generate_trajectory_files) then
            error stop 'error: kernel generation requires the trajectory file to be exported'
        else
            write(*,*) '* Generate BSP kernel'
            mkspk_input = 'solution_'//solver%mission%get_case_name()//'.txt'
            bsp_output  = 'solution_'//solver%mission%get_case_name()//'.bsp'
            mkspk_setup = 'mkspk_'//solver%mission%get_case_name()//'.txt'
            pck_output  = 'solution_'//solver%mission%get_case_name()//'.tpc.json'
            !note: have to delete the kernel if it is already there or mkspk will fail.
            call delete_file(bsp_output)
            call generate_mkspk_setup_file(mkspk_setup)
            call generate_pck_file(pck_output)
            call execute_command_line(mkspk_path//' -setup '//mkspk_setup//' -input '//mkspk_input//' -output '//bsp_output)
        end if
    end if
    if (debug) then
        write(*,*) 'SOLUTION:'
        call solver%mission%define_problem_size(n_segs=n_segs)
        do iseg = 1, n_segs
            call solver%mission%segs(iseg)%get_inputs(x0_rotating=x_rotating)
            write(*,'(I5, *(F15.6,1X))') iseg, x_rotating
        end do
    end if
    if (solver%mission%generate_defect_file) then
        write(*,'(A)') ' * Generate defect file'
        call solver%mission%print_constraint_defects('defects_'//&
                                                     solver%mission%get_case_name()//&
                                                     '.csv')
    end if
    if (solver%mission%generate_json_trajectory_file) then
        call solver%mission%export_trajectory_json_file('traj_'//solver%mission%get_case_name())
    end if
    if (solver%mission%generate_eclipse_files) then
        call solver%mission%generate_eclipse_data('eclipse', &
                                                  filetype = solver%mission%eclipse_filetype)
    end if
    if (solver%mission%run_pyvista_script) then
        write(*,'(A)') ' * Run PyVista script'
        !mkspk_input = 'solution_'//solver%mission%get_case_name()//'.txt'
        mkspk_input = 'traj_'//solver%mission%get_case_name()//'.json'
        call execute_command_line('python ./python/plot_utilities.py '//mkspk_input, wait=.false.)
    end if
    write(*,'(A)') ' * HALO done'
    write(*,'(A)') ''
    end subroutine halo_solver_main
Call graph
halo_solver_main calls constraint_violations, define_problem_size, delete_file, export_trajectory_json_file, generate_eclipse_data, generate_mkspk_setup_file, generate_pck_file, get_case_name, get_segment_inputs, initialize_the_solver, plot_trajectory, print_constraint_defects, put_x_in_segments, write_optvars_to_file, solve, status
constraint_violations calls put_x_in_segments, get_problem_arrays, propagate_segment, segs_to_propagate
export_trajectory_json_file calls add, create_array, create_object, destroy, initialize, insert_after, compute_rdot_vecs, destroy_trajectory, export_rp_ra_json_file, propagate_segment
generate_eclipse_data calls get_case_name, add, icrf_frame, initialize, destroy_trajectory, get_sun_fraction, propagate_segment, transform, two_body_rotating_frame
generate_mkspk_setup_file calls int_to_string
generate_pck_file calls add, destroy, initialize, int_to_string
get_case_name calls int_to_string
initialize_the_solver calls define_problem_size, put_x_in_segments, status, initialize, get_sparsity_pattern, get_x_from_json_file, initialize_the_mission, read_config_file
plot_trajectory calls get_case_name, add_3d_plot, add_sphere, initialize, destroy_trajectory, propagate_segment, savefig
print_constraint_defects calls define_problem_size, get_problem_arrays
put_x_in_segments calls define_problem_size, extract_vector, set_segment_inputs
write_optvars_to_file calls get_case_name, add, create_array, create_object, destroy, initialize, insert_after
export_rp_ra_json_file calls solve, add, destroy, initialize, evaluate
get_problem_arrays calls fill_vector, compute_rdot
get_sparsity_pattern calls define_problem_size
get_sun_fraction calls apparent_position, cubic_shadow_model, from_j2000moon_to_j2000ssb
get_x_from_json_file calls get, get_child, info, load
initialize_the_mission calls define_problem_size, destroy, initialize, get_problem_arrays, get_sparsity_pattern, set_segment_inputs, initialize_splinded_ephemeris, magnitude, get_scales_from_segs, set_dpert, set_sparsity_pattern
propagate_segment calls icrf_frame, transform, two_body_rotating_frame, first_call, integrate, set_segment_outputs
read_config_file calls initialize, evaluate, get, generate_patch_points, read_epoch, update_epoch
segs_to_propagate calls define_problem_size
set_segment_inputs calls icrf_frame, transform, two_body_rotating_frame
apparent_position calls axis_angle_rotation, cross, get_r, unit
cubic_shadow_model calls acosd, asind, unit, wrap_angle
from_j2000moon_to_j2000ssb calls icrf_frame, transform
generate_patch_points calls initialize, first_call, integrate, compute_crtpb_parameter
get_scales_from_segs calls define_problem_size, fill_vector
read_epoch calls get, jd_to_et, julian_date
update_epoch calls calendar_date_to_et, et_to_jd, julian_date_to_calendar_date
get_char calls get
get_int calls get
get_logical calls get
get_real calls get
get_real_vec calls get