set_segment_outputs – halo
set_segment_outputs Subroutine
8 statements
Source File
public subroutine set_segment_outputs(me, xf, xf_rotating)
Set the outputs of a segment, assuming it has been propagated elsewhere
Type Bound
segment
Arguments
Type Intent Optional Attributes Name
class(segment), intent(inout) :: me
real(kind=wp), intent(in), dimension(6) :: xf
inertial frame
real(kind=wp), intent(in), dimension(6) :: xf_rotating
inertial frame
Called by
Source Code
    subroutine set_segment_outputs(me,xf,xf_rotating)
    implicit none
    class(segment),intent(inout) :: me
    real(wp),dimension(6),intent(in) :: xf  !! inertial frame
    real(wp),dimension(6),intent(in) :: xf_rotating  !! inertial frame
    me%data%xf = xf
    me%data%xf_rotating = xf_rotating
    end subroutine set_segment_outputs
Call graph
propagate_segment calls set_segment_outputs
constraint_violations calls propagate_segment
plot_trajectory calls propagate_segment
halo_solver calls constraint_violations, plot_trajectory