write_optvars_to_file – halo
write_optvars_to_file Subroutine
20 statements
Source File
public subroutine write_optvars_to_file(me, filename, x)
Write the current x variables to a file (compatible with the Copernicus optvar file).
Type Bound
mission_type
Arguments
Type Intent Optional Attributes Name
class(mission_type), intent(inout) :: me
character(len=*), intent(in) :: filename
file name [without extension]
real(kind=wp), intent(in), dimension(:) :: x
solver opt vars vector
Calls
Called by
Source Code
    subroutine write_optvars_to_file(me,filename,x)
    implicit none
    class(mission_type),intent(inout) :: me
    character(len=*),intent(in)       :: filename !! file name [without extension]
    real(wp),dimension(:),intent(in)  :: x        !! solver opt vars vector
    integer           :: i     !! counter
    type(json_file)   :: json  !! for writing the solution file
    character(len=10) :: istr  !! x index string
    call json%initialize()
    do i = 1, size(x)
        write(istr,'(I10)') i
        istr = adjustl(istr)
        call json%add('xvec('//trim(istr)//').i',i) ! var counter
        call json%add('xvec('//trim(istr)//').label',trim(me%xname(i)))
        call json%add('xvec('//trim(istr)//').value',x(i)*me%xscale(i))  ! unscaled value
        call json%add('xvec('//trim(istr)//').scale',me%xscale(i))
    end do
    call json%print_file(trim(filename)//'_'//me%get_case_name()//'.json')
    call json%destroy()
    end subroutine write_optvars_to_file
Call graph
write_optvars_to_file calls add, destroy, initialize, print_file, get_case_name
halo_solver calls write_optvars_to_file