channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.10
  - matplotlib=3.8.3
  - liblapack=3.9.0
  - libopenblas=0.3.24
  - cmake=3.27.4
  - metis=5.1.0
  - fortran-compiler=1.6.0
  - cxx-compiler=1.6.0
  - c-compiler=1.6.0
  - fpm=0.10.0
  - pyvista=0.43.3
  - trame-vtk=2.8.5
  - trame=3.5.2
  - nest-asyncio=1.6.0
  - trame-vuetify=2.4.2